language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
env:
  global:
  - secure: ii9nhNojy3uWv9V5AwzL4XnuSOfcZozeB94TxfaKEHsikd//nRnTbgL9j5xXxN/1GZvn/2Uyc9VOTvQoKCVsqjO4p0Rsg+AabrF1Q3O6nQlz30Kg8qFtYTxYffmQTNTB1UxDtkSlrRqb3dv0h3WH31Cwox1y9c6020W1nxxMKWg=
  - secure: XFSob0TrqVQye9kuxJ5y+puh9KyipD05ttPak4sII3MWtYzezxqr7oJHFcF2i4l4CCoNqGZxavHExoTlwFCsboXYakm0Eb6XT6PrSOJfQwZj3ocg8LR9n7aF+yLssglMAgnEbYUh+kureC43/Oca7PUCAW2aITKpjybi7FUXcjk=
  - secure: Fme0/EUBpUkDvn/zVusPmbCPDXpPNrICRkxz558vR703+E6RRIgZ2/s/+xOEFOx/NgAqOy7so9XLno8DHSNgZ7pz1pe+lVKJ2yk4eWhcVjguozA6zoqEP3XMa4dsJZICUljUooI9yeSpTkD16a8CslAMeqxWV8RTtGCRJMLaO3U=
deploy:
  provider: rubygems
  gem: factor-connector-newrelic
  api_key:
    secure: Ku9G4ArcMhgVr/Vr8L+K9TQaKM0x69FZsIzq3S3i/kJqUMmnqQlZqo/V6EKbe8uqt3hKCwR/jTyv76PFw166VMTIE7ZwZjuM6M8tbrRIdtSBzY6Aonydc9vZbAEWZPtU+SDG3UmbT0yx+eF4qdfBH/M+sDDYchUwToo8ctW65oE=
  on:
    tags: true
    all_branches: true
